site_name: Cheatsheets and Checklists

markdown_extensions:
  - footnotes
exclude_docs: |
    index_template.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
