site_name: Cheatsheets and Checklists

markdown_extensions:
  - footnotes
  - pymdownx.tilde
exclude_docs: |
    index_template.md
site_url: https://cheatsheets-and-checklists.pages.dev/
repo_url: https://github.com/buckmanc/cheatsheets_and_checklists
site_author: Charles Buckman
site_description: A simple repo of personal reference material written in Markdown. Peruse at your leisure, preferably with a cup of bean water in a cozy tavern run by an orc.

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
